# Generated by Django 5.1.2 on 2024-12-13 13:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moneyFUS", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("email", "is_active"),
                name="unique_active_email",
            ),
        ),
    ]
