# Generated by Django 5.1.2 on 2024-12-13 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moneyFUS", "0002_alter_user_email_alter_user_user_id_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_active_email",
        ),
    ]
