# Generated by Django 5.1.2 on 2024-12-14 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moneyFUS", "0003_remove_user_unique_active_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userauth",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
