# Generated by Django 5.1.2 on 2025-02-10 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyFUS', '0005_usagecategory_assetlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagecategory',
            name='category_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Lend',
            fields=[
                ('lend_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_to_user', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lend_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
