# Generated by Django 5.1.2 on 2025-02-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneyFUS', '0009_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usagecategory',
            old_name='category_code',
            new_name='usage_category_code',
        ),
        migrations.RenameField(
            model_name='usagecategory',
            old_name='category_id',
            new_name='usage_category_id',
        ),
        migrations.RenameField(
            model_name='usagecategory',
            old_name='category_name',
            new_name='usage_category_name',
        ),
    ]
