# Generated by Django 5.1.2 on 2025-02-16 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyFUS', '0010_rename_category_code_usagecategory_usage_category_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('split_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SplitDetail',
            fields=[
                ('split_detail_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL)),
                ('split_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='moneyFUS.split')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('split_id', 'participant_id'), name='unique_split_participant')],
            },
        ),
    ]
