services:
  frontend:
    build:
      context: frontend
      target: dev
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 6006:6006
  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./db-data/dev:/var/lib/mysql
    env_file:
      - ./backend/.env
    expose:
      - 3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u $$MYSQL_USER -p$$MYSQL_PASSWORD | grep 'mysqld is alive'"]
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 60s
  backend:
    build:
      context: backend
      target: dev
    volumes:
      - ./backend/:/app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
