services:
  frontend:
    build:
      context: frontend
      target: deploy
    volumes:
      - ./frontend/:/app
    ports:
      - 443:3000
  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./db-data/prod:/var/lib/mysql
    environment:
      - MYSQL_ROOT_HOST=127.*.*.*
    env_file:
      - ./backend/.env
    expose:
      - 3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u $$MYSQL_USER -p$$MYSQL_PASSWORD | grep 'mysqld is alive'"]
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 60s
  backend:
    build:
      context: backend
      target: deploy
    volumes:
      - ./backend/:/app
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy
